### ISSUE TITLE
Gnome extension doesn't work in Ubuntu Gnome 14.04

### ISSUE THREAD

**Issue by forteller** [screenfreeze/deskcon-android#11]
I put the extension folder in the correct place, but it did not show up in the tweak tool. It's probably not compatible. Also: You should add it to the official extentions website for easier installation and for more people to learn about your program.

Thanks!

**Comment by screenfreeze** [comment]
Hi, I fixed a Bug in 14.04 now, so try it out. But you should least see the extension in the Tweak Tool.
What Gnome Version do you have? Type 'gnome-shell --version' in Terminal.
