### ISSUE TITLE
Still running in background after turning off Gnome Extension

### ISSUE THREAD

**Issue by forteller** [screenfreeze/deskcon-android#12]
Steps to reproduce:
- Install the extension and turn it on
- Turn it off again
- Restart computer and note in the System Monitor that the DeskCon server is still running in the background.

It sees that the extension adds the DeskCon server to the list of Startup Applications when installed or turned on, but doesn't remove it again from that list when it's turned off.

**Comment by screenfreeze** [comment]
The Server and Desktop Extension are seperate. The Extension does not start the deskcon-server, it just connects to it. To disable autostart of the Server, disable it in the System Startup Settings or uninstall the package. In Gnome 3.10 it's just called 'Startup Programs' I think.

**Comment by forteller** [comment]
But can the server part do anything useful without the extension turned on? If yes, then this behavior is OK. But if not, the turning off the extension should also remove the server from the list of startup applications.

**Comment by screenfreeze** [comment]
The Server shows Desktop Notifications on new Calls,SMS,... and handels incoming Files.
