### ISSUE TITLE
No deskcon accessibility entry

### ISSUE THREAD

**Issue by hotice** [screenfreeze/deskcon-android#14]
I've installed DeskCon v 0.2.8 via Android Play and I can't get it to work because I can't enable it under Accessibility since there's no Deskcon entry there...

This occurs on a Samsung Galaxy S2 running CyanogenMod 11 (dev) / Android 4.4.2.

**Comment by screenfreeze** [comment]
Hi, I will look into the problem this weekend.

**Comment by screenfreeze** [comment]
a workaround for now would be Android Settings > Security > Notification Access and check DeskCon there.

**Comment by screenfreeze** [comment]
this should be fixed in the next release 0.2.9

**Comment by hotice** [comment]
It was indeed fixed (there's no DeskCon under Security > Notification Access though) but it doesn't seem to work: the Unity indicator displays "-1" for Battery, Volume, Str: http://i.imgur.com/hbH19b8.png And also, when trying to send a file from the desktop, nothing happens (it works the other way though)...

**Comment by screenfreeze** [comment]
yeah, the unity indicator didn't save the ip of your android device. The status report of the android device needs to come first, I will fix that. For now you could try this. Do a reboot of your Desktop.
When everything is loaded, set the status intervall in the android app to 20 for example. After a few minutes a normal status should be in the indicator and file transfer should work.

**Comment by hotice** [comment]
Indeed, a restart gets it working. Looking forward to the fix too, so I can write about DeskCon on my blog.

Thanks!
