### ISSUE TITLE
Can't compose or reply to a message

### ISSUE THREAD

**Issue by wilf1rst** [screenfreeze/deskcon-android#6]
I installed the last software version 0.2.1
I receive the sms notification but i can't compose message or reply to it.
The message box won't even open.

desktop:
ubuntu 13.10
gnome-shell 3.10.2.1

phone:
xiaomi mi2s
rom miui 4.2.21

**Comment by screenfreeze** [comment]
That was a little problem with the deb package, I uploaded a fixed file yesterday, so re-download the Server Package and reinstall. Let me know, if it works, maybe it is another bug.

**Comment by wilf1rst** [comment]
I just reinstalled the server and now the message aren't displayed.
I see unreaded message on the gnome-shell extensions but no notification. 
The compose message text disappear too.
![menu_011](https://f.cloud.github.com/assets/6798484/2276474/ea5762d0-9f33-11e3-9900-b4b049e4b26a.png)

**Comment by screenfreeze** [comment]
Does a Ping work (tap on your Computername in the Desktop Hosts List) ?
I'll look into it tomorrow.

**Comment by wilf1rst** [comment]
The ping command work.
![espace de travail 1_012](https://f.cloud.github.com/assets/6798484/2276580/40afe62e-9f35-11e3-8a2b-43b56b8492b3.png)

thanks.

**Comment by wilf1rst** [comment]
here my configuration of deskcon on the phone 
![screenshot_2014-02-26-23-41-47 resized](https://f.cloud.github.com/assets/6798484/2276877/f39334f0-9f38-11e3-8a66-2ab69d0b9afe.png)
![screenshot_2014-02-26-23-42-06 resized](https://f.cloud.github.com/assets/6798484/2276879/fa89e240-9f38-11e3-8d59-190df1177d66.png)

I reinstalled the gnome-shell-extensions and I have the compose message text back but after a reboot it disappear again.

edit: after a while the compose message text reappear but i'm ever unable to use the fonction

**Comment by screenfreeze** [comment]
yes the reply Button wasn't working, it's fixed in the Desktop Version, so download it from git master or wait for next deb release. You don't need to have the Messages App in the Notification Whitelist. 
I'm working on the delay next.
