### ISSUE TITLE
Gnome shell extension is blocked

### ISSUE THREAD

**Issue by fabrixx** [screenfreeze/deskcon-android#7]
Gnome shell extension in Debian testing (jessie x64) is loaded . I see only icon but can't open any setting panel.

I can pair my device correctly but not receive notifications.

Gnome-shell 3.8

**Comment by screenfreeze** [comment]
Maybe the a Server Error, did you install from Deb package or Git Source?
When you run deskcon-server in Terminal are there any Errors?

**Comment by fabrixx** [comment]
I installed the Deb package
Process deskon-server is loaded in task manager (active in background)

I receive:
fabrizio@debian:~$ deskcon-server
Traceback (most recent call last):
  File "main.py", line 289, in <module>
    main()
  File "main.py", line 284, in main
    app = Connector()
  File "main.py", line 44, in **init**
    self.server = self.TCPServer((HOST, PORT), self.TCPHandler, self)
  File "main.py", line 179, in **init**
    SocketServer.TCPServer.**init**(self, server_address, RequestHandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in **init**
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Indirizzo già in uso (Address already in use)

**Comment by screenfreeze** [comment]
looks like another Process on your machine uses Port uses port 8082 or 8083 already.
You can change the Ports to something else in the config file ~/.deskcon/config.conf.

Also, deskcon-server is not the main Process. The main Process is "main.py"
It's Bug I need to fix, but runs fine as it is now.

**Comment by fabrixx** [comment]
But authentication process worked correctly. I see windows with auth codes
i clicked yes and on the phones i see associated.

I cant click on shell addon icon that is blocked.

2014-03-10 21:00 GMT+01:00 screenfreeze notifications@github.com:

**Comment by screenfreeze** [comment]
The Gnome Shell extension won't show anything, till an Android Device sends his Information to your Desktop. Could you try the Version from Github and tap on your Desktop in the Android App, it
should ping the Desktop. If you want, we could try solving the problem in a IRC chat.

**Comment by fabrixx** [comment]
Now is ok!! I reassociate desktop  and now i can receive notifications and
send messages.

Great!!

2014-03-11 13:10 GMT+01:00 screenfreeze notifications@github.com:

**Comment by screenfreeze** [comment]
good to hear :)
