### ISSUE TITLE
Use default SMS application for sending messages

### ISSUE THREAD

**Issue by icaruseffect** [screenfreeze/deskcon-android#9]
Hi,
I changed my default SMS application to text-secure and set it as standard, but messages typed from the desktop (gnome-shell addon) are still send by the android system SMS/MMS-application. 
Because of this the messages are no more collected in one place but spread over the default sms database and the texsecure database.

Improvement: deskcon-android uses the default messaging app for sending messages

Possible problems: e.g. textsecure allows to encrypt the whole SMS database when not in use, I'm not sure how much this could cause complications.
Best regards and thank you for this useful app

**Comment by screenfreeze** [comment]
HI, deskcon sends sms via the system SmsManager, but thats not the Problem. As far as I understand , Text-secure stores sms/mms in its own Database and not in the System Database.
So I don't get access to Text-secures DB.

**Comment by icaruseffect** [comment]
OK then it's not possible. Thank you for your investigation. 
I will stick to my workaround to import them and delete the messages from the sytem messaging app.
